package org.jpc.util;

import java.io.File;
import java.util.Properties;

import org.minitoolbox.commons.Preferences;

public class JpcPreferences extends Preferences {

	//General JPC properties
	public static final String JPC_NAME = "The Java-Prolog Connectivity Library";
	public static final String JPC_SHORT_NAME = "JPC";
	
	//Configuration file
	public static final String CONFIGURATION_FILE = JPC_SHORT_NAME.toLowerCase() + ".settings";
	
	//Prolog resources properties
	public static final String JPC_BASE_PACKAGE = "org.jpc";
	public static final String JPC_PROLOG_PACKAGE = JPC_BASE_PACKAGE + ".pl"; //base package for Prolog files required by JPC
	public static final String JPC_PROLOG_RESOURCES = JPC_PROLOG_PACKAGE.replaceAll("\\.", "/") + "/";
	public static final String JPC_LOADER_FILE = JPC_PROLOG_RESOURCES + "jpc.pl";
	public static final String JPC_LOGTALK_LOADER_FILE = JPC_PROLOG_RESOURCES + "jpc_logtalk.lgt";
	
	//Macros symbols
	public static final String SUBSTITUTION_OPERATOR = "?";
	public static final String CONVERSION_SPECIFIER_OPERATOR = "/";
	public static final String TERM_CONVERSION_BY_MAPPING_SYMBOL = "m";
	public static final String TERM_CONVERSION_BY_REFERENCE_SYMBOL = "r";
	public static final String TERM_CONVERSION_BY_MAPPING_AND_REFERENCE_SYMBOL = TERM_CONVERSION_BY_MAPPING_SYMBOL + TERM_CONVERSION_BY_REFERENCE_SYMBOL;
	public static final String TERM_CONVERSION_BY_SERIALIZATION_SYMBOL = "s";
	public static final String DEFAULT_TERM_CONVERSION_SYMBOL = TERM_CONVERSION_BY_MAPPING_SYMBOL;
	
	
	public final static String HOME_ENV_VAR = "HOME";
	
	//Prefix for all the variables exclusive to JPC (used by the library in certain cases, not directly written by the user). Variables starting with this prefix are generated by the framework. These variables are not dropped from the query result.
	public static final String JPC_VAR_PREFIX = "JPC_VAR_";
	//Similar to JPC_VAR_PREFIX. However, Variables starting with this prefix should not be visible in the result.
	public static final String JPC_ANON_VAR_PREFIX = "_"+JPC_VAR_PREFIX;
	
	
	public JpcPreferences() {
	}
	
	public JpcPreferences(Properties properties) {
		super(properties);
	}
	
	private File getHomeDirectory() {
		String homeDirVar = this.getVarOrThrow(HOME_ENV_VAR);
		return new File(homeDirVar);
	}
	
	protected String getJpcTmpSubdirectoryName() {
		return "."+JPC_SHORT_NAME.toLowerCase();
	}

	public File getJpcTmpDirectory() {
		File homeDir = getHomeDirectory();
		return new File(homeDir, getJpcTmpSubdirectoryName());
	}

}

